// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace qa_automation_mars.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Language Functionality")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class LanguageFunctionalityFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Language Functionality", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "LanguagePage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a new language")]
        [NUnit.Framework.CategoryAttribute("mars")]
        [NUnit.Framework.CategoryAttribute("language")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "Marati", "Fluent", null)]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "longTextInputslongTextInputslongTextInputslongTextInputslongTextInputs", "Fluent", null)]
        public async System.Threading.Tasks.Task AddANewLanguage(string email, string password, string languageValue, string levelValue, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mars",
                    "language"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add a new language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
await testRunner.WhenAsync(string.Format("I add a new language \'{0}\' and \'{1}\'", languageValue, levelValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
await testRunner.ThenAsync(string.Format("New language should be successfully created \'{0}\'", languageValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit an existing language")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "Spanish", "Basic", null)]
        public async System.Threading.Tasks.Task EditAnExistingLanguage(string email, string password, string languageValue, string levelValue, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit an existing language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
await testRunner.WhenAsync(string.Format("I update an existing language \'{0}\' and \'{1}\'", languageValue, levelValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
await testRunner.ThenAsync(string.Format("The updated language with modified data should be successfully updated \'{0}\'", languageValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete an existing language")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", null)]
        public async System.Threading.Tasks.Task DeleteAnExistingLanguage(string email, string password, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete an existing language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
await testRunner.WhenAsync("I delete an existing language", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
await testRunner.ThenAsync("The existing language should be successfully removed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify adding same language with different lauguage levels")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "English", "Basic", "Fluent", null)]
        public async System.Threading.Tasks.Task VerifyAddingSameLanguageWithDifferentLauguageLevels(string email, string password, string languageValue, string levelValue, string levelValuetwo, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            argumentsOfScenario.Add("levelValuetwo", levelValuetwo);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify adding same language with different lauguage levels", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
await testRunner.WhenAsync(string.Format("I add same language with different language levels \'{0}\' and \'{1}\' and \'{2}\'", languageValue, levelValue, levelValuetwo), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
await testRunner.ThenAsync("An error message should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Attempt to add the same language twice")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "English", "Basic", null)]
        public async System.Threading.Tasks.Task AttemptToAddTheSameLanguageTwice(string email, string password, string languageValue, string levelValue, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attempt to add the same language twice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 42
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
await testRunner.WhenAsync(string.Format("I add same language twice with same language level \'{0}\' and \'{1}\'", languageValue, levelValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("An error message language is already exist in your language list should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Try to add an empty language")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "\"\"", "Choose Language Level", null)]
        public async System.Threading.Tasks.Task TryToAddAnEmptyLanguage(string email, string password, string languageValue, string levelValue, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Try to add an empty language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
await testRunner.WhenAsync(string.Format("I add an empty language \'{0}\' and \'{1}\'", languageValue, levelValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
await testRunner.ThenAsync("An error message Please enter language and level should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Try to add a language without selecting language level")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "English", "Choose Language Level", null)]
        public async System.Threading.Tasks.Task TryToAddALanguageWithoutSelectingLanguageLevel(string email, string password, string languageValue, string levelValue, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Try to add a language without selecting language level", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
await testRunner.WhenAsync(string.Format("I add a new language \'{0}\' and  empty language level \'{1}\'", languageValue, levelValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
await testRunner.ThenAsync("An error message Please enter language and level should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Try to add more than four languages")]
        [NUnit.Framework.TestCaseAttribute("ShirishaG.@g.com", "123456", "English", "Fluent", null)]
        public async System.Threading.Tasks.Task TryToAddMoreThanFourLanguages(string email, string password, string languageValue, string levelValue, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("languageValue", languageValue);
            argumentsOfScenario.Add("levelValue", levelValue);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Try to add more than four languages", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
await testRunner.GivenAsync(string.Format("I logged into mars application successfully \'{0}\' and \'{1}\'", email, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
await testRunner.WhenAsync(string.Format("I add four languages \'{0}\' and  \'{1}\'", languageValue, levelValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
await testRunner.ThenAsync("I should not add fifth language", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
